(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1905021827420",f:(function(AMP,_){
var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function n(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ia=b.prototype};function ha(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ia(a){return new Promise(function(b){b(a())})}function ja(){var a,b,c;this.la=new Promise(function(a,d){b=a;c=d});this.Aa=b;this.za=c;this.ca=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ja.prototype.add=function(a){var b=this,c=++this.ca;Promise.resolve(a).then(function(a){b.ca===c&&b.Aa(a)},function(a){b.ca===c&&b.za(a)});return this.la};
ja.prototype.then=function(a,b){return this.la.then(a,b)};function ka(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var la=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ma(a){var b=Object.create(null);if(!a)return b;for(var c;c=la.exec(a);){var d=ka(c[1],c[1]),e=c[2]?ka(c[2],c[2]):"";b[d]=e}return b};var na="";
function p(){var a,b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=ma(c.location.originalHash||c.location.hash);d=d.spt;var g=ma(c.location.search);na||(na=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011905021827420");c=b.AMP_MODE={localDev:!1,development:!("1"!=f.development&&!c.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],minified:!0,lite:void 0!=g.amp_lite,test:e,log:f.log,version:"1905021827420",rtvVersion:na,singlePassType:d}}return c}
;var oa=Object.prototype.toString;function pa(a){return a?Array.prototype.slice.call(a):[]}function qa(a){return"[object Object]"===oa.call(a)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var q=self.log;function r(){if(!q.user)throw Error("failed to call initLogConstructor");return q.user}function t(){if(q.dev)return q.dev;throw Error("failed to call initLogConstructor");}function u(a,b,c,d){r().assert(a,b,c,d,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function v(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(ra(d,b)){var f=w(d,b);if(f)return f}if(!c)return null}a=x(a);a=y(a);return ra(a,b)?w(a,b):null}function z(a,b){a=a.__AMP_TOP||a;return w(a,b)}function A(a,b){var c=x(a);c=y(c);return w(c,b)}function sa(a,b){return ta(y(a),b)}function x(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function y(a){a=x(a);return a.isSingleDoc()?a.win:a}
function w(a,b){ra(a,b);var c=ua(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ta(a,b){var c=ua(a)[b];if(c){if(c.promise)return c.promise;w(a,b);return c.promise=Promise.resolve(c.obj)}return null}function ua(a){var b=a.services;b||(b=a.services={});return b}function ra(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}
function va(){var a=new ha,b=a,c=b.promise,d=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:d,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var wa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function xa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};var ya;var za=Object.prototype.hasOwnProperty;function B(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function C(a){return a||{}}
function Aa(a,b){var c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.G=b.t;a.B=b.s;a.T=b.d;if(d.includes(a.B))throw Error("Source object has a circular reference.");d.push(a.B);a.G!==a.B&&(a.T>c?Object.assign(a.G,a.B):Object.keys(a.B).forEach(function(a){return function(b){var c=a.B[b];if(za.call(a.G,b)){var d=a.G[b];if(qa(c)&&qa(d)){e.push({t:d,s:c,d:a.T+1});return}}a.G[b]=c}}(a)));a={B:a.B,G:a.G,T:a.T}}};function Ba(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function Ca(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function Da(a){var b="fieldset";/^[\w-]+$/.test(b);b=b.toUpperCase();return Ca(a,function(a){return a.tagName==b})}function D(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)};function Ea(a,b,c){var d=sa(a,b);if(d)return d;var e=x(a);return e.whenBodyAvailable().then(function(){var a=e.win;var b=e.win.document.head;if(b){var d=[];b=b.querySelectorAll("script[custom-element]");for(var k=0;k<b.length;k++)d.push(b[k].getAttribute("custom-element"))}else d=[];a=d.includes(c)?z(a,"extensions").waitForExtension(a,c):Promise.resolve();return a}).then(function(){var d=e.win;if(d.ampExtendedElements&&d.ampExtendedElements[c]){d=y(a);var g=ta(d,b);g?d=g:(d=ua(d),d[b]=va(),d=d[b].promise)}else d=
null;return d})};function E(a){return A(a,"resources")};var F,Fa="Webkit webkit Moz moz ms O o".split(" ");function Ga(a,b,c){var d;var e=a.style;if(!Ba(b,"--")){F||(F=B());var f=F[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var h=0;h<Fa.length;h++){var k=Fa[h]+g;if(void 0!==e[k]){g=k;break b}}g=""}void 0!==e[g]&&(f=g)}F[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function Ha(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};var G;function Ia(a,b,c){var d=void 0,e=a,f=c;var g=function(a){try{return f(a)}catch(Z){throw self.reportError(Z),Z;}};var h=Ja(),k=!1;d&&(k=d.capture);e.addEventListener(b,g,h?d:k);return function(){e&&e.removeEventListener(b,g,h?d:k);g=e=f=null}}function Ja(){if(void 0!==G)return G;G=!1;try{var a={get capture(){G=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return G};function Ka(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a}function La(a,b,c){return Ia(a,b,c)}function Ma(a,b){var c=b,d=Ia(a,"mouseup",function(a){try{c(a)}finally{c=null,d()}});return d}function Na(a){var b,c,d=new Promise(function(b){c=Ma(a,b)});d.then(c,c);b&&b(c);return d};function Oa(a,b){function c(c){g=null;f=a.setTimeout(d,e);b.apply(null,c)}function d(){f=0;g&&c(g)}var e=100,f=0,g=null;return function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];f?g=b:c(b)}};function Pa(a){var b=a.getRootNode();this.wa=b.ownerDocument||b;this.l=this.wa.defaultView;this.ia=A(a,"viewport");this.P=[];this.P.push(La(b,"input",function(a){a=a.target;"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)}));this.P.push(La(b,"mousedown",function(a){1==a.which&&(a=a.target,"TEXTAREA"==a.tagName&&Ra(a))}));var c=b.querySelectorAll("textarea");this.P.push(La(b,"amp:dom-update",function(){c=b.querySelectorAll("textarea")}));var d=Oa(this.l,function(a){a.relayoutAll&&Sa(c)});
this.P.push(this.ia.onResize(d));D(c,function(a){Ta(a).then(function(b){b&&(r().warn("AMP-FORM",'"textarea[autoexpand]" with initially scrolling content will not autoexpand.\nSee https://github.com/ampproject/amphtml/issues/20839'),a.removeAttribute("autoexpand"))})})}function Ua(a){function b(){var b=c.querySelector("textarea[autoexpand]");b&&!d?d=new Pa(a):!b&&d&&(d.dispose(),d=null)}var c=a.getRootNode(),d=null;Ia(c,"amp:dom-update",b);b()}Pa.prototype.dispose=function(){this.P.forEach(function(a){return a()})};
function Ta(a){var b=E(a);return b.measureElement(function(){return a.scrollHeight>a.clientHeight})}function Sa(a){D(a,function(a){"TEXTAREA"==a.tagName&&a.hasAttribute("autoexpand")&&Qa(a)})}function Ra(a){var b=E(a);Promise.all([b.measureElement(function(){return a.scrollHeight}),Na(a)]).then(function(c){var d=c[0],e=0;return b.measureMutateElement(a,function(){e=a.scrollHeight},function(){d!=e&&a.removeAttribute("autoexpand")})})}
function Qa(a){var b=E(a),c=a.ownerDocument.defaultView,d=0,e=0,f=0,g=Va(a);b.measureMutateElement(a,function(){var b=c.getComputedStyle(a)||B();e=a.scrollHeight;var k=parseInt(b.getPropertyValue("max-height"),10);f=isNaN(k)?Infinity:k;d="content-box"==b.getPropertyValue("box-sizing")?-parseInt(b.getPropertyValue("padding-top"),10)+-parseInt(b.getPropertyValue("padding-bottom"),10):parseInt(b.getPropertyValue("border-top-width"),10)+parseInt(b.getPropertyValue("border-bottom-width"),10)},function(){return g.then(function(b){a.classList.toggle("i-amphtml-textarea-max",
b+d>f);var c="iAmphtmlHasExpanded"in a.dataset,g=c||e<=b;g&&(a.dataset.iAmphtmlHasExpanded="",Ga(a,"height",b+d+"px"))})})}
function Va(a){var b=a.ownerDocument,c=b.defaultView,d=b.body,e=E(a),f=a.cloneNode(!1);f.classList.add("i-amphtml-textarea-clone");var g=0,h=!1;return e.measureMutateElement(d,function(){var b=c.getComputedStyle(a)||B();b=parseInt(b.getPropertyValue("max-height"),10);h=isNaN(b)||a.scrollHeight<b},function(){h&&(a.scrollTop=0);b.body.appendChild(f)}).then(function(){return e.measureMutateElement(d,function(){g=f.scrollHeight},function(){var a=f;a.parentElement&&a.parentElement.removeChild(a)})}).then(function(){return g})}
;function Wa(a,b){return a.hasAttribute("verify-xhr")?new Xa(a,b):new Ya(a)}function H(a){this.h=a}H.prototype.onCommit=function(){Za(this);return ab(this)?this.qa():Promise.resolve({updatedElements:[],errors:[]})};H.prototype.qa=function(){return Promise.resolve({updatedElements:[],errors:[]})};
function ab(a){a=a.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled)switch(c.type){case "select-multiple":case "select-one":c=c.options;for(var d=0;d<c.length;d++)if(c[d].selected!==c[d].defaultSelected)return!0;break;case "checkbox":case "radio":if(c.checked!==c.defaultChecked)return!0;break;default:if(c.value!==c.defaultValue)return!0}}return!1}function Za(a){(a=a.h.elements)&&D(a,function(a){a.setCustomValidity("")})}function Ya(a){H.apply(this,arguments)}n(Ya,H);
function Xa(a,b){this.h=a;this.X=b;this.S=null;this.ka=[]}n(Xa,H);Xa.prototype.qa=function(){var a=this,b=this.X().then(function(){return[]},function(a){return bb(a)});return cb(this,b).then(function(b){return db(a,b)})};function cb(a,b){if(!a.S){a.S=new ja;var c=function(){return a.S=null};a.S.then(c,c)}return a.S.add(b)}
function db(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.ka;a.ka=b;for(var f=0;f<b.length;f++){var g=b[f],h=r().assertString(g.name,"Verification errors must have a name property");g=r().assertString(g.message,"Verification errors must have a message property");h=r().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(g),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function bb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function eb(){this.o=null}l=eb.prototype;l.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};l.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};l.removeAll=function(){this.o&&(this.o.length=0)};l.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};l.getHandlerCount=function(){return this.o?this.o.length:0};function fb(){this.ja=new eb}fb.prototype.beforeSubmit=function(a){return this.ja.add(a)};fb.prototype.fire=function(a){this.ja.fire(a)};function gb(){var a=100;this.va=a;this.ba=this.ha=0;this.W=Object.create(null)}gb.prototype.has=function(a){return!!this.W[a]};gb.prototype.get=function(a){var b=this.W[a];if(b)return b.access=++this.ba,b.payload};gb.prototype.put=function(a,b){this.has(a)||this.ha++;this.W[a]={payload:b,access:this.ba};if(!(this.ha<=this.va)){t().warn("lru-cache","Trimming LRU cache");a=this.W;var c=this.ba+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.ha--)}};var I=self.AMP_CONFIG||{},hb={thirdParty:I.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:I.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof I.thirdPartyFrameRegex?new RegExp(I.thirdPartyFrameRegex):I.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:I.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof I.cdnProxyRegex?new RegExp(I.cdnProxyRegex):I.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:I.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:I.localDev||!1};var ib=C({c:!0,v:!0,a:!0,ad:!0,action:!0}),jb,kb,lb=/[?&]amp_js[^&]*/,mb=/[?&]amp_gsa[^&]*/,nb=/[?&]amp_r[^&]*/,ob=/[?&]amp_kit[^&]*/,pb=/[?&]usqp[^&]*/;
function J(a){var b;jb||(jb=self.document.createElement("a"),kb=self.UrlCache||(self.UrlCache=new gb));var c=b?null:kb,d=jb;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=p().test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,d);a=d}return a}function qb(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function rb(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function sb(a){"string"==typeof a&&(a=J(a));var b=a;"string"==typeof b&&(b=J(b));if(!hb.cdnProxyRegex.test(b.origin))return a.href;b=a.pathname.split("/");u(ib[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);u(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");var e;e=(e=a.search)&&"?"!=e?(e=e.replace(lb,"").replace(mb,"").replace(nb,"").replace(ob,"").replace(pb,"").replace(/^[?&]/,
""))?"?"+e:"":"";return b+e+(a.hash||"")};function K(a){for(var b=a.elements,c={},d=/^(?:input|select|textarea)$/i,e=/^(?:submit|button|image|file|reset)$/i,f=/^(?:checkbox|radio)$/i,g={},h=0;h<b.length;g={F:g.F},h++){var k=b[h],m=k,Z=m.checked;g.F=m.name;var Yb=m.multiple,Zb=m.options,$b=m.tagName,$a=m.type;m=m.value;!g.F||tb(k)||!d.test($b)||e.test($a)||f.test($a)&&!Z||(void 0===c[g.F]&&(c[g.F]=[]),Yb?D(Zb,function(a){return function(b){b.selected&&c[a.F].push(b.value)}}(g)):c[g.F].push(m))}var Q=ub(a);Q&&Q.name&&(a=Q.name,void 0===c[a]&&
(c[a]=[]),c[Q.name].push(Q.value));Object.keys(c).forEach(function(a){0==c[a].length&&delete c[a]});return c}function ub(a){var b=a.elements,c=b.length,d=a.ownerDocument.activeElement,e=null;for(a=0;a<c;a++){var f=b[a],g=f.type;if("BUTTON"==f.tagName||"submit"==g)if(e||(e=f),d==f)return d}return e}function tb(a){if(a.disabled)return!0;a=Da(a);for(var b=0;b<a.length;b++)if(a[b].disabled)return!0;return!1};function vb(a,b){var c=z(a,"platform");return c.isIos()&&11==c.getMajorVersion()?new wb(b):FormData.prototype.entries&&FormData.prototype.delete?new L(b):new M(b)}function M(a){this.C=a?K(a):B()}M.prototype.append=function(a,b){var c=String(a);this.C[c]=this.C[c]||[];this.C[c].push(String(b))};M.prototype.delete=function(a){delete this.C[a]};
M.prototype.entries=function(){var a=this,b=[];Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.push([c,a])})});var c=0;return{next:function(){return c<b.length?{value:b[c++],done:!1}:{value:void 0,done:!0}}}};M.prototype.getFormData=function(){var a=this,b=new FormData;Object.keys(this.C).forEach(function(c){a.C[c].forEach(function(a){return b.append(c,a)})});return b};function L(a){this.D=new FormData(a);a&&(a=ub(a))&&this.append(a.name,a.value)}
L.prototype.append=function(a,b){this.D.append(a,b)};L.prototype.delete=function(a){this.D.delete(a)};L.prototype.entries=function(){return this.D.entries()};L.prototype.getFormData=function(){return this.D};function wb(a){L.call(this,a);var b=this;a&&D(a.elements,function(a){"file"==a.type&&0==a.files.length&&(b.D.delete(a.name),b.D.append(a.name,new Blob([]),""))})}n(wb,L);
wb.prototype.append=function(a,b,c){b&&"object"==typeof b&&""==b.name&&0==b.size?this.D.append(a,new Blob([]),c||""):this.D.append(a,b)};var xb=["GET","POST"];
function yb(a,b){u(qa(a),"Object expected: %s",a);var c="document"==b;if(!c)return new Response(a.body,a.init);var d=B(),e={status:200,statusText:"OK",getResponseHeader:function(a){return d[String(a).toLowerCase()]||null}};if(a.init){var f=a.init;Array.isArray(f.headers)&&f.headers.forEach(function(a){var b=a[0],c=a[1];d[String(b).toLowerCase()]=String(c)});f.status&&(e.status=parseInt(f.status,10));f.statusText&&(e.statusText=String(f.statusText))}return new Response(a.body?String(a.body):"",e)}
function zb(a){var b=a.getAttribute("cross-origin")||a.getAttribute("crossorigin");return b&&"amp-viewer-auth-token-via-post"===b.trim()?Ea(a,"amp-viewer-assistance","amp-viewer-assistance").then(function(a){u(a,'crossorigin="amp-viewer-auth-token-post" requires amp-viewer-assistance extension.');return a.getIdTokenPromise()}).then(function(a){return a||""}).catch(function(){return""}):Promise.resolve(void 0)};function N(a,b){var c="amp-form";this.L=a;this.A=b;this.Ba=c}N.prototype.isSupported=function(){var a=this.L.ampdoc;return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.L.hasCapability("viewerRenderTemplate"):!1};N.prototype.fetchAndRenderTemplate=function(a,b,c,d){c=void 0===c?null:c;d=void 0===d?{}:d;var e;c||(e=this.A.maybeFindTemplate(a));return this.L.sendMessageAwaitResponse("viewerRenderTemplate",Ab(this,b,e,c,d))};
N.prototype.renderTemplate=function(a,b){if(this.isSupported()){u("string"===typeof b.html,"Server side html response must be defined");var c=this.A.findAndSetHtmlForTemplate(a,b.html)}else c=Array.isArray(b)?this.A.findAndRenderTemplateArray(a,b):this.A.findAndRenderTemplate(a,b);return c};
function Ab(a,b,c,d,e){e=void 0===e?{}:e;var f=C({type:a.Ba}),g="successTemplate",h=d&&d[g]?d[g]:c;h&&(f[g]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",m=d&&d[k]?d[k]:null;m&&(f[k]={type:"amp-mustache",payload:m.innerHTML});e&&Object.assign(f,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){c=c.body;b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);
b.body=d}return C({originalRequest:{input:a,init:b},ampComponent:f})}N.prototype.verifySsrResponse=function(a,b,c){b=yb(b,c.fetchOpt.responseType);c=c.fetchOpt;(b=b.headers.get("AMP-Access-Control-Allow-Source-Origin"))?(a=J(sb(a.location.href)).origin,u(b==a,"Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: "+b+(" vs "+a))):c.requireAmpResponseSourceOrigin&&u(!1,"Response must contain the AMP-Access-Control-Allow-Source-Origin header")};function Bb(a,b){this.ga=b;this.ia=A(a,"viewport");this.ra=z(a.win,"vsync");this.ea=null;this.da="";this.Z=!1;this.J=a.win.document.createElement("div");Ha(this.J,!1);this.J.classList.add("i-amphtml-validation-bubble");this.J.__BUBBLE_OBJ=this;a.getBody().appendChild(this.J)}Bb.prototype.isActiveOn=function(a){return this.Z&&a==this.ea};Bb.prototype.hide=function(){this.Z&&(this.Z=!1,this.ea=null,this.da="",this.ra.run({measure:void 0,mutate:Cb},{bubbleElement:this.J}))};
Bb.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.da){this.Z=!0;this.ea=a;this.da=b;var c={message:b,targetElement:a,bubbleElement:this.J,viewport:this.ia,id:this.ga};this.ra.run({measure:Db,mutate:Eb},c)}};function Cb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ha(a.bubbleElement,!1)}function Db(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function Eb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ha(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a)Ga(b,
d,a[d])};var Fb,Gb,Hb=0;function O(a){this.form=a;this.ampdoc=x(a);this.resources=E(a);this.root=this.ampdoc.getRootNode();this.Y=null}l=O.prototype;l.report=function(){};l.onBlur=function(){};l.onInput=function(){};l.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};
l.checkInputValidity=function(a){if("TEXTAREA"===a.tagName&&a.hasAttribute("pattern")&&(a.checkValidity()||"Please match the requested format."===a.validationMessage)){var b=a.getAttribute("pattern"),c=new RegExp("^"+b+"$","m"),d=c.test(a.value);a.setCustomValidity(d?"":"Please match the requested format.")}return a.checkValidity()};l.checkFormValidity=function(a){Ib(this,a);return a.checkValidity()};l.reportFormValidity=function(a){Ib(this,a);return a.reportValidity()};
function Ib(a,b){D(b.elements,function(b){"TEXTAREA"==b.tagName&&a.checkInputValidity(b)})}l.fireValidityEventIfNecessary=function(){var a=this.Y;this.Y=this.checkFormValidity(this.form);if(a!==this.Y){var b=Ka(this.form.ownerDocument.defaultView,this.Y?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};function Jb(a){O.apply(this,arguments)}n(Jb,O);Jb.prototype.report=function(){this.reportFormValidity(this.form);this.fireValidityEventIfNecessary()};
function P(a){O.call(this,a);var b="i-amphtml-validation-bubble-"+Hb++;this.R=new Bb(this.ampdoc,b)}n(P,O);P.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){a[b].focus();this.R.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};P.prototype.onBlur=function(a){"submit"!=a.target.type&&this.R.hide()};
P.prototype.onInput=function(a){a=a.target;this.R.isActiveOn(a)&&(this.checkInputValidity(a)?(a.removeAttribute("aria-invalid"),this.R.hide()):(a.setAttribute("aria-invalid","true"),this.R.show(a,a.validationMessage)))};function R(a){O.call(this,a)}n(R,O);l=R.prototype;l.reportInput=function(a){var b=Kb(a);b&&this.showValidationFor(a,b)};l.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
l.getValidationFor=function(a,b){if(!a.id)return null;"TEXTAREA"===a.tagName&&(b="patternMismatch");var c="__AMP_VALIDATION_"+b;c in a||(a[c]=this.root.querySelector("[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]")));return a[c]};
l.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.__AMP_VISIBLE_VALIDATION=c,this.resources.mutateElement(a,function(){return a.setAttribute("aria-invalid","true")}),this.resources.mutateElement(c,function(){return c.classList.add("visible")}))};
l.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,this.resources.mutateElement(a,function(){return a.removeAttribute("aria-invalid")}),this.resources.mutateElement(b,function(){return b.classList.remove("visible")}))};l.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};l.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
l.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!this.checkInputValidity(a)&&this.reportInput(a)};l.onBlur=function(a){this.onInteraction(a)};l.onInput=function(a){this.onInteraction(a)};function Lb(a){R.apply(this,arguments)}n(Lb,R);Lb.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!this.checkInputValidity(a[b])){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
Lb.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function S(a){R.apply(this,arguments)}n(S,R);S.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)this.checkInputValidity(b[c])||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};S.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function Mb(a){R.apply(this,arguments)}n(Mb,R);
Mb.prototype.shouldValidateOnInteraction=function(){return!0};Mb.prototype.onInteraction=function(a){R.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function Nb(a){S.apply(this,arguments)}n(Nb,S);Nb.prototype.shouldValidateOnInteraction=function(){return!0};Nb.prototype.onInteraction=function(a){S.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function Ob(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new Mb(a);case "show-all-on-submit":return new S(a);case "interact-and-submit":return new Nb(a);case "show-first-on-submit":return new Lb(a)}a.ownerDocument&&void 0===Fb&&(Fb=!!document.createElement("form").reportValidity);return Fb?new Jb(a):new P(a)}
function Kb(a){var b=["badInput"];for(c in a.validity)b.includes(c)||b.push(c);var c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};function Pb(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Qb(b));var c=b.FormProxy,d=new c(a);"action"in d||Rb(a,d);a.$p=d}
function Qb(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,f=[a.HTMLFormElement,a.EventTarget],g=f.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);g.forEach(function(b){var d={},f;for(f in b){d.w=a.Object.getOwnPropertyDescriptor(b,f);if(d.w&&f.toUpperCase()!=f&&!Ba(f,"on")&&!e.hasOwnProperty.call(c,f))if("function"==typeof d.w.value)d.aa=d.w.value,c[f]=function(a){return function(){return a.aa.apply(this.h,
arguments)}}(d);else{var g={};d.w.get&&(g.get=function(a){return function(){return a.w.get.call(this.h)}}(d));d.w.set&&(g.set=function(a){return function(b){return a.w.set.call(this.h,b)}}(d));a.Object.defineProperty(c,f,g)}d={aa:d.aa,w:d.w}}});return b}
function Rb(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c){d.j=e;if(!(d.j in b||d.j.toUpperCase()==d.j||Ba(d.j,"on"))){d.m=Sb[d.j];var f=a[d.j];if(d.m)if(d.m.access==T){d.N=void 0;if(f&&f.nodeType){var g=c=f,h=g.nextSibling;g=g.parentNode;g.removeChild(c);try{d.N=a[d.j]}finally{g.insertBefore(c,h)}}else d.N=f;Object.defineProperty(b,d.j,{get:function(a){return function(){return a.N}}(d)})}else d.m.access==U&&(d.O=d.m.attr||d.j,Object.defineProperty(b,
d.j,{get:function(c){return function(){var d=b.getAttribute(c.O);return null==d&&void 0!==c.m.def?c.m.def:c.m.type==Tb?"true"===d:c.m.type==Ub?null!=d:c.m.type==Vb?(d=d||"",v(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.m.type==Ub&&(c=c?"":null);null!=c?b.setAttribute(a.O,c):b.removeAttribute(a.O)}}(d)}));else Object.defineProperty(b,d.j,{get:function(b){return function(){return a[b.j]}}(d),set:function(b){return function(c){a[b.j]=c}}(d)})}d={N:d.N,O:d.O,m:d.m,j:d.j}}}
var U=1,T=2,Vb=1,Tb=2,Ub=3,Sb={acceptCharset:{access:U,attr:"accept-charset"},accessKey:{access:U,attr:"accesskey"},action:{access:U,type:Vb},attributes:{access:T},autocomplete:{access:U,def:"on"},children:{access:T},dataset:{access:T},dir:{access:U},draggable:{access:U,type:Tb,def:!1},elements:{access:T},encoding:{access:T},enctype:{access:U},hidden:{access:U,type:Ub,def:!1},id:{access:U,def:""},lang:{access:U},localName:{access:T},method:{access:U,def:"get"},name:{access:U},noValidate:{access:U,
attr:"novalidate",type:Ub,def:!1},prefix:{access:T},spellcheck:{access:U},style:{access:T},target:{access:U,def:""},title:{access:U},translate:{access:U}};function Wb(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}textarea[autoexpand]:not(.i-amphtml-textarea-max){overflow:hidden!important}.i-amphtml-textarea-clone{visibility:hidden;position:absolute;top:-9999px;left:-9999px;height:0!important}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{color:red}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",f=a.getHeadNode(),g=Xb(f,ac(f,c),d||!1,e||null);if(b){var h=a.getRootNode();if(bc(h,g))b(g);else var k=setInterval(function(){bc(h,g)&&(clearInterval(k),b(g))},4)}}
function Xb(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=B());var f=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,g=c?"amp-runtime":f?"amp-extension="+d:null;if(g){var h=cc(a,e,g);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var m=null;c?k.setAttribute("amp-runtime",""):f?(k.setAttribute("amp-extension",d||""),m=cc(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),m=a.lastChild);b=m;a.insertBefore(k,b?b.nextSibling:a.firstChild);
g&&(e[g]=k);return k}function cc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function ac(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function bc(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function dc(a,b,c){Ea(a,"amp-analytics-instrumentation","amp-analytics").then(function(d){d&&d.triggerEventForTarget(a,b,c)})};var ec=["amp-selector"];
function fc(a,b){var c=this;try{Pb(a)}catch(f){t().error("amp-form","form proxy failed to install",f)}a.__AMP_FORM=this;this.ga=b;this.l=a.ownerDocument.defaultView;this.Da=z(this.l,"timer");this.pa=v(a,"url-replace");this.fa=null;this.h=a;this.A=z(this.l,"templates");this.Ga=z(this.l,"xhr");this.V=v(this.h,"action");this.na=E(this.h);this.L=A(this.h,"viewer");this.K=new N(this.L,this.A);this.H=(this.h.getAttribute("method")||"GET").toUpperCase();this.Ca=this.h.getAttribute("target");this.M=gc(this,
"action-xhr");this.Fa=gc(this,"verify-xhr");this.oa=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.oa||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");this.I="initial";b=this.h.elements;for(var d=0;d<b.length;d++){var e=b[d].name;u("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,b[d])}this.$=Ob(this.h);this.Ea=Wa(this.h,function(){return hc(c)});this.V.installActionHandler(this.h,this.ua.bind(this));
ic(this);jc(this);this.ma=this.ta=null;this.xa=A(a,"form-submit-service")}function gc(a,b){var c=a.h.getAttribute(b);if(c){var d=v(a.h,"url");d.assertHttpsUrl(c,a.h,b);u(!d.isProxyOrigin(c),"form %s should not be on AMP CDN: %s",b,a.h)}return c}l=fc.prototype;
l.requestForFormFetch=function(a,b,c,d){var e="GET"==b||"HEAD"==b;if(e){kc(this);var f=K(this.h);d&&d.forEach(function(a){delete f[a]});c&&Aa(f,c);var g=qb(a,rb(f))}else{g=a;var h=vb(this.l,this.h);d&&d.forEach(function(a){h.delete(a)});for(var k in c)h.append(k,c[k])}var m={xhrUrl:g,fetchOpt:C({body:h,method:b,credentials:"include",headers:C({Accept:"application/json"})})};return zb(this.h).then(function(a){a&&(u("POST"==m.fetchOpt.method,"Cannot attach auth token with GET request."),h.append("ampViewerAuthToken",
a));return m})};l.setXhrAction=function(a){this.M=a};l.ua=function(a){var b=this;if(!a.satisfiesTrust(100))return null;if("submit"==a.method)return lc(this).then(function(){var c=a;return"submitting"!=b.I&&mc(b)?nc(b,c.trust,null):Promise.resolve(null)});"clear"===a.method&&oc(this);return null};function lc(a){if(a.fa)return a.fa;var b=a.h.querySelectorAll(ec.join(",")),c=pa(b).map(function(a){return a.whenBuilt()});return a.fa=pc(a,c,2E3)}
function ic(a){a.L.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});a.h.addEventListener("submit",a.ya.bind(a),!0);a.h.addEventListener("blur",function(b){qc(b.target);a.$.onBlur(b)},!0);a.K.isSupported()||a.h.addEventListener("change",function(b){a.Ea.onCommit().then(function(c){var d=c.updatedElements,e=c.errors;d.forEach(qc);a.$.onBlur(b);"verifying"===a.I&&(e.length?(V(a,"verify-error"),W(a,{verifyErrors:e}).then(function(){X(a,"verify-error",
e)})):V(a,"initial"))})});a.h.addEventListener("input",function(b){qc(b.target);a.$.onInput(b)})}function jc(a){Ea(a.h,"inputmask","amp-inputmask").then(function(a){a&&a.install()})}function rc(a,b){sc(a,"Form analytics not supported");var c=C({}),d=K(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;dc(a.h,b,c)}
function oc(a){a.h.reset();V(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");D(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");D(c,function(a){a.classList.remove("visible")});tc(a.h)}
l.ya=function(a){if("submitting"==this.I||!mc(this))return a.stopImmediatePropagation(),a.preventDefault(),Promise.resolve(null);(this.M||"POST"==this.H)&&a.preventDefault();return nc(this,100,a)};
function nc(a,b,c){try{var d={form:a.h,actionXhrMutator:a.setXhrAction.bind(a)};a.xa.fire(d)}catch(k){t().error("amp-form","Form submit service failed: %s",k)}var e=uc(a),f=a.h.getElementsByClassName("i-amphtml-async-input");if(!a.M&&"GET"==a.H){sc(a,"Non-XHR GETs not supported.");kc(a);if(0===f.length){for(d=0;d<e.length;d++)a.pa.expandInputValueSync(e[d]);var g=!c;vc(a,g);return Promise.resolve()}c&&c.preventDefault()}V(a,"submitting");var h=[];h.push(wc(a,e));D(f,function(b){h.push(xc(a,b))});
return pc(a,h,1E4).then(function(){if(a.M)var c=yc(a,b);else"POST"==a.H?u(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h):"GET"==a.H&&vc(a,!0),c=Promise.resolve();return c},function(b){return zc(a,b)})}function uc(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function zc(a,b){V(a,"submit-error");t().error("amp-form","Form submission failed: %s",b);var c=C({error:b.message});W(a,c).then(function(){X(a,"submit-error",b)})}
function hc(a){if("submitting"===a.I)return Promise.resolve();V(a,"verifying");X(a,"verify",null);return wc(a,uc(a)).then(function(){return Ac(a)})}function yc(a,b){a.K.isSupported()?b=Bc(a,b):(Cc(a,b),b=a.X(a.M,a.H).then(function(b){return Dc(a,b)},function(b){return Ec(a,b)}));p().test&&(a.ta=b);return b}
function Bc(a,b){var c,d=K(a.h);return W(a,d).then(function(){return a.V.trigger(a.h,"submit",null,b)}).then(function(){return a.requestForFormFetch(a.M,a.H)}).then(function(b){var d=c=b,e=c.fetchOpt||{};var h=e.method;void 0===h?h="GET":(h=h.toUpperCase(),xb.includes(h));e.method=h;e.headers=e.headers||C({});d.fetchOpt=e;d=c;var k=a.l;h=c.xhrUrl;e=c.fetchOpt;!1===e.ampCors&&(e.requireAmpResponseSourceOrigin=!1);!0===e.requireAmpResponseSourceOrigin&&t().error("XHR","requireAmpResponseSourceOrigin is deprecated, use ampCors instead");
void 0===e.requireAmpResponseSourceOrigin&&(e.requireAmpResponseSourceOrigin=!0);k=k.origin||J(k.location.href).origin;h=J(h).origin;k==h&&(e.headers=e.headers||{},e.headers["AMP-Same-Origin"]="true");d.fetchOpt=e;d=c;e=c.xhrUrl;!1!==c.fetchOpt.ampCors&&(h=a.l,k=J(e),k=ma(k.search),u(!("__amp_source_origin"in k),"Source origin is not allowed in %s",e),h=J(sb(h.location.href)).origin,h=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(h),e=qb(e,h,void 0));d.xhrUrl=e;return a.K.fetchAndRenderTemplate(a.h,
c,Fc(a))}).then(function(b){return Gc(a,b,c)},function(b){return Hc(a,b)})}function Fc(a){var b=a.h.querySelector("div[submit-success]"),c=a.h.querySelector("div[submit-error]"),d,e;b&&(d=a.A.maybeFindTemplate(b));c&&(e=a.A.maybeFindTemplate(c));return{successTemplate:d,errorTemplate:e}}function Hc(a,b){V(a,"submit-error");r().error("amp-form","Form submission failed: %s",b);return ia(function(){W(a,b||{}).then(function(){X(a,"submit-error",b)})})}
function Cc(a,b){rc(a,"amp-form-submit");var c=K(a.h);W(a,c).then(function(){a.V.trigger(a.h,"submit",null,b)})}function wc(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.pa.expandInputValueAsync(b[d]));return pc(a,c,100)}
function xc(a,b){return b.getImpl().then(function(a){return a.getValue()}).then(function(c){var d=b.getAttribute("name");d=a.h.querySelector("input[name="+String(d).replace(wa,xa)+"]");if(!d){d=C({name:b.getAttribute("name"),hidden:"true"});var e=a.l.document.createElement("input"),f;for(f in d)e.setAttribute(f,d[f]);d=e}d.setAttribute("value",c);a.h.appendChild(d)})}
function Ac(a){var b=pa(a.h.querySelectorAll("["+"no-verify".replace(wa,xa)+"]")),c=b.map(function(a){return a.name||a.id}),d={};return a.X(a.Fa,a.H,(d.__amp_form_verify=!0,d),c)}l.X=function(a,b,c,d){var e=this;sc(this,"XHRs should be proxied.");return this.requestForFormFetch(a,b,c,d).then(function(a){return e.Ga.fetch(a.xhrUrl,a.fetchOpt)})};function Gc(a,b,c){a.K.verifySsrResponse(a.l,b,c);return Ic(a,ia(function(){return b}))}
function Dc(a,b){return Ic(a,b.json()).then(function(){rc(a,"amp-form-submit-success");Jc(a,b)})}function Ic(a,b){return b.then(function(b){V(a,"submit-success");W(a,b||{}).then(function(){X(a,"submit-success",b)})},function(a){r().error("amp-form","Failed to parse response JSON: %s",a)})}
function Ec(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){rc(a,"amp-form-submit-error");V(a,"submit-error");W(a,c||{}).then(function(){X(a,"submit-error",c)});Jc(a,b.response);r().error("amp-form","Form submission failed: %s",b)})}function vc(a,b){rc(a,"amp-form-submit");b&&a.h.submit();V(a,"initial")}function sc(a,b){var c=a.K.isSupported();u(!1===c,"[amp-form]: viewerRenderTemplate | %s",b)}
function kc(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");u(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function mc(a){void 0===Gb&&(Gb=!!a.l.document.createElement("input").checkValidity);if(Gb){var b=Kc(a.h);if(a.oa)return a.$.report(),b}return!0}
function Jc(a,b){sc(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){u("_blank"!=a.Ca,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=v(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){u(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}A(a.h,"navigation").navigateTo(a.l,c,"AMP-Redirect-To")}}}
function X(a,b,c){c=Ka(a.l,"amp-form."+b,C({response:c}));a.V.trigger(a.h,b,c,100)}function pc(a,b,c){return Promise.race([Promise.all(b),a.Da.promise(c)])}
function V(a,b){var c=a.I;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);var d=a.h.querySelector("["+c+"]");if(d){/^[\w-]+$/.test("i-amphtml-rendered");if(void 0!==ya)var e=ya;else{try{var f=d.ownerDocument,g=f.createElement("div"),h=f.createElement("div");g.appendChild(h);e=g.querySelector(":scope div")===h}catch(k){e=!1}e=ya=e}e?d=d.querySelector("> [i-amphtml-rendered]".replace(/^|,/g,"$&:scope ")):(d.classList.add("i-amphtml-scoped"),e="> [i-amphtml-rendered]".replace(/^|,/g,
"$&.i-amphtml-scoped "),e=d.querySelectorAll(e),d.classList.remove("i-amphtml-scoped"),d=void 0===e[0]?null:e[0]);d&&d.parentElement&&d.parentElement.removeChild(d)}a.I=b}
function W(a,b){var c=a.h.querySelector("["+a.I+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.ga;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.A.hasTemplate(c)?d=a.K.renderTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");return a.na.mutateElement(c,function(){c.appendChild(b);var d=Ka(a.l,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)})}):a.na.mutateElement(c,function(){})}p().test&&(a.ma=
d);return d}l.Ha=function(){return this.ma};l.Ja=function(){return this.ta};function Kc(a){D(a.querySelectorAll("input,select,textarea,fieldset"),function(a){return Y(a)});return Y(a)}function tc(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.U=d;var e=a.querySelectorAll("."+String(c.U).replace(wa,xa));D(e,function(a){return function(b){b.classList.remove(a.U)}}(c));c={U:c.U}}}
function Y(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var f in a.validity)a.classList.toggle(f,a.validity[f]);if(b&&c){f=Da(a);for(var g=0;g<f.length;g++)Y(f[g]);
a.form&&Y(a.form)}return e}function qc(a){Y(a,!0)}function Lc(a){this.sa=Mc(a).then(function(){return Nc(a)});p().test&&this.sa.then(function(){var b=a.win,c=Ka(b,"amp:form-service:initialize",null,{bubbles:!0});b.dispatchEvent(c)})}Lc.prototype.whenInitialized=function(){return this.sa};function Mc(a){var b=new ha;Wb(a,b.resolve);return b.promise}function Nc(a){return a.whenReady().then(function(){var b=a.getRootNode();Oc(b.querySelectorAll("form"));Ua(a);Pc(b)})}
function Oc(a){a&&D(a,function(a,c){var b=a.__AMP_FORM||null;b||new fc(a,"amp-form-"+c)})}function Pc(a){a.addEventListener("amp:dom-update",function(){Oc(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("form-submit-service",fb);a.registerServiceForDoc("amp-form",Lc)})(self.AMP);
})});

//# sourceMappingURL=amp-form-0.1.js.map

(self.AMP=self.AMP||[]).push({n:"amp-sidebar",v:"1905021827420",f:(function(AMP,_){
var h="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;function u(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var v=self.log;function w(){if(!v.user)throw Error("failed to call initLogConstructor");return v.user}function x(a,b){return w().assert(a,'"toolbar-target" is required',b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0)};function y(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(z(d,b)){var f=A(d,b);if(f)return f}if(!c)return null}a=B(a);a=C(a);return z(a,b)?A(a,b):null}function D(a,b){a=a.__AMP_TOP||a;return A(a,b)}function F(a,b){var c=B(a);c=C(c);return A(c,b)}function B(a){return a.nodeType?D((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function C(a){a=B(a);return a.isSingleDoc()?a.win:a}
function A(a,b){z(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function z(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var G;function H(a){return":not([toolbar]) [autoscroll]".replace(/^|,/g,"$&"+a+" ")};function I(){var a,b=Object.create(null);a&&Object.assign(b,a);return b};function J(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function K(a,b){return a.closest?a.closest(b):J(a,function(a){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1})}function aa(a){var b=a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr";return"rtl"==b};var L,M="Webkit webkit Moz moz ms O o".split(" ");function N(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function O(a,b){if(void 0!==G)var c=G;else{try{var d=b.ownerDocument,e=d.createElement("div"),f=d.createElement("div");e.appendChild(f);c=e.querySelector(":scope div")===f}catch(l){c=!1}c=G=c}c?c=b.querySelector(H(":scope")):(b.classList.add("i-amphtml-scoped"),c=H(".i-amphtml-scoped"),c=b.querySelectorAll(c),b.classList.remove("i-amphtml-scoped"),c=void 0===c[0]?null:c[0]);if(c){var g=(a.win.getComputedStyle(b)||I())["overflow-y"];if("scroll"!=g&&"auto"!=g)w().error("AMP-SIDEBAR","for 'autoscroll', 'nav [toolbar]' element must be set to overflow\n        'scroll' or 'auto' for 'autoscroll' to work.");
else{var k=F(a,"viewport");k.animateScrollWithinParent(c,b,"center",0)}}};function P(a,b){this.I=b;this.c=a;this.B=b.getAmpDoc();this.R=this.c.getAttribute("toolbar");this.A=null;this.h=void 0;this.D=!1;this.c.classList.add("amp-sidebar-toolbar-target-hidden");ba(this)}P.prototype.onLayoutChange=function(){var a=this.B.win.matchMedia(this.R).matches;a?ca(this):da(this)};
function ba(a){a.A=a.c.cloneNode(!0);var b=x(a.c.getAttribute("toolbar-target"),a.c);a.B.whenReady().then(function(){var c=a.B.getElementById(b);if(c)a.h=c,a.A.classList.add("i-amphtml-toolbar"),N(a.h,!1);else throw Error("Could not find the toolbar-target element with an id: "+b);})}
function ca(a){a.D?Promise.resolve():a.I.mutateElement(function(){a.h&&(N(a.h,!0),a.h.contains(a.A)||a.h.appendChild(a.A),a.c.classList.add("amp-sidebar-toolbar-target-shown"),a.c.classList.remove("amp-sidebar-toolbar-target-hidden"),a.D=!0,O(a.B,a.A))})}function da(a){a.D&&a.I.mutateElement(function(){a.h&&(N(a.h,!1),a.c.classList.add("amp-sidebar-toolbar-target-hidden"),a.c.classList.remove("amp-sidebar-toolbar-target-shown"),a.D=!1)})};function Q(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function R(a){a=AMP.BaseElement.call(this,a)||this;a.m=null;a.G=null;a.M=null;a.o=null;a.l=a.win.document;a.N=a.l.documentElement;a.w=null;a.L=[];var b=D(a.win,"platform");a.K=b.isIos();a.O=b.isSafari();a.C=-1;a.H=!1;a.F=null;a.J=0;return a}var S=AMP.BaseElement;R.prototype=h(S.prototype);R.prototype.constructor=R;if(r)r(R,S);else for(var T in S)if("prototype"!=T)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(S,T);V&&Object.defineProperty(R,T,V)}else R[T]=S[T];R.S=S.prototype;
R.prototype.buildCallback=function(){var a=this,b=this.element;b.classList.add("i-amphtml-overlay");b.classList.add("i-amphtml-scrollable");this.w=b.getAttribute("side");this.m=this.getViewport();this.G=y(b,"action");"left"!=this.w&&"right"!=this.w&&(this.w=ea(this,aa(this.l)?"right":"left"),b.setAttribute("side",this.w));var c=u(b.querySelectorAll("nav[toolbar]"));c.forEach(function(b){try{a.L.push(new P(b,a))}catch(g){a.user().error("amp-sidebar toolbar","Failed to instantiate toolbar",g)}});this.K&&
fa(this);W(this)?X(this):b.setAttribute("aria-hidden","true");b.hasAttribute("role")||b.setAttribute("role","menu");b.tabIndex=-1;this.N.addEventListener("keydown",function(b){"Escape"==b.key&&a.j()&&b.preventDefault()});var d=b.getAttribute("data-close-button-aria-label")||"Close the sidebar",e=this.l.createElement("button");e.textContent=d;e.classList.add("i-amphtml-screen-reader");e.tabIndex=-1;e.addEventListener("click",function(){a.j()});b.appendChild(e);this.registerDefaultAction(function(b){return X(a,
b)},"open");this.registerAction("toggle",this.P.bind(this));this.registerAction("close",this.j.bind(this));b.addEventListener("click",function(c){if((c=K(c.target,"A"))&&c.href){var d=y(b,"url").parse(c.href),e=a.getAmpDoc().win.location.href;Q(c.href)==Q(e)&&d.hash&&a.j()}},!0)};R.prototype.onLayoutMeasure=function(){var a=this;this.getAmpDoc().whenReady().then(function(){a.L.forEach(function(a){a.onLayoutChange()})})};function W(a){return a.element.hasAttribute("open")}
R.prototype.P=function(a){W(this)?this.j():X(this,a)};function Y(a,b,c){function d(){a.M===b&&a.mutateElement(b)}a.M=b;c?D(a.win,"timer").delay(d,c):d()}function ha(a){N(a.element,!0);a.m.addToFixedLayer(a.element,!0);a.K&&a.O&&ia(a);a.element.scrollTop=1;Y(a,function(){return ja(a)})}
function ja(a){ka(a);a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");Y(a,function(){var b=a.getRealChildren();a.scheduleLayout(b);a.scheduleResume(b);try{a.element.focus()}catch(c){}Z(a,"sidebarOpen")},350);O(a.getAmpDoc(),a.element)}
function la(a){a.o&&a.o.classList.toggle("i-amphtml-ghost",!0);a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");Y(a,function(){N(a.element,!1);a.schedulePause(a.getRealChildren());Z(a,"sidebarClose")},350)}function X(a,b){W(a)||(a.m.enterOverlayMode(),Y(a,function(){return ha(a)}),F(a.getAmpDoc(),"history").push(a.j.bind(a)).then(function(b){a.C=b}),b&&(a.F=b.caller,a.J=a.m.getScrollTop()))}
R.prototype.j=function(){var a=this;if(!W(this))return!1;this.m.leaveOverlayMode();var b=this.J==this.m.getScrollTop(),c=this.element.contains(this.l.activeElement);Y(this,function(){return la(a)});-1!=this.C&&(F(this.getAmpDoc(),"history").pop(this.C),this.C=-1);if(this.F&&c&&b)try{this.F.focus()}catch(d){}return!0};function ea(a,b){return K(a.element,"amp-story")?"left"==b?"right":"left":b}
function ka(a){if(!a.o){var b=a.l.createElement("div");b.classList.add("i-amphtml-sidebar-mask");b.addEventListener("click",function(){a.j()});a.element.ownerDocument.body.appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.o=b}a.o.classList.toggle("i-amphtml-ghost",!1)}
function fa(a){a.element.addEventListener("scroll",function(b){W(a)&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}
function ia(a){if(!a.H){var b=a.l.createElement("div"),c={height:"29px",width:"100%","background-color":"transparent"},d;for(d in c){var e=b,f=c[d];var g=e.style;var k=d;if(2>k.length?0:0==k.lastIndexOf("--",0))g=k;else{L||(L=I());var l=L[k];if(!l){l=k;if(void 0===g[k]){var t=k.charAt(0).toUpperCase()+k.slice(1);b:{for(var E=0;E<M.length;E++){var U=M[E]+t;if(void 0!==g[U]){t=U;break b}}t=""}void 0!==g[t]&&(l=t)}L[k]=l}g=l}g&&(e.style[g]=f)}a.element.appendChild(b);a.H=!0}}
function Z(a,b){var c=a.win;var d="amp-sidebar toolbar."+b;var e={};var f={detail:e};Object.assign(f,void 0);"function"==typeof c.CustomEvent?d=new c.CustomEvent(d,f):(c=c.document.createEvent("CustomEvent"),c.initCustomEvent(d,!!f.bubbles,!!f.cancelable,e),d=c);a.G.trigger(a.element,b,d,100)}(function(a){a.registerElement("amp-sidebar",R,"amp-sidebar{position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:2147483647;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;-webkit-transform:translateX(-100%)!important;transform:translateX(-100%)!important}amp-sidebar[side=right]{right:0!important;-webkit-transform:translateX(100%)!important;transform:translateX(100%)!important}amp-sidebar[side][open]{-webkit-transform:translateX(0)!important;transform:translateX(0)!important}amp-sidebar[side]{-webkit-transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1),-webkit-transform 233ms cubic-bezier(0,0,.21,1)}.i-amphtml-toolbar>ol,.i-amphtml-toolbar>ul{display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-pack:start;-ms-flex-pack:start;justify-content:flex-start;-ms-flex-wrap:wrap;flex-wrap:wrap;overflow:auto;list-style-type:none;padding:0;margin:0}.i-amphtml-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:2147483646}\n/*# sourceURL=/extensions/amp-sidebar/0.1/amp-sidebar.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-sidebar-0.1.js.map

(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"1905021827420",f:(function(AMP,_){
var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ba={a:!0},p={};try{p.__proto__=ba;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;
function r(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(q)q(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ca=b.prototype};function ca(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function t(){this.l=null}f=t.prototype;f.add=function(a){var b=this;this.l||(this.l=[]);this.l.push(a);return function(){b.remove(a)}};f.remove=function(a){this.l&&(a=this.l.indexOf(a),-1<a&&this.l.splice(a,1))};f.removeAll=function(){this.l&&(this.l.length=0)};f.fire=function(a){if(this.l)for(var b=this.l,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.l?this.l.length:0};function v(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function w(a){var b=Object.create(null);if(!a)return b;for(var c;c=da.exec(a);){var d=v(c[1],c[1]),e=c[2]?v(c[2],c[2]):"";b[d]=e}return b};var x="";
function y(a){var b=a||self;if(b.AMP_MODE)var c=b.AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,g=w(c.location.originalHash||c.location.hash);d=d.spt;var h=w(c.location.search);x||(x=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011905021827420");c=b.AMP_MODE={localDev:!1,development:!("1"!=g.development&&!c.AMP_DEV_MODE),examiner:"2"==g.development,filter:g.filter,geoOverride:g["amp-geo"],minified:!0,lite:void 0!=h.amp_lite,test:e,log:g.log,version:"1905021827420",rtvVersion:x,singlePassType:d}}return c}
;function z(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var A=self.log;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user};function ea(a){var b,c=a.ownerDocument.defaultView,d=c!=(c.__AMP_TOP||c);if(d){if(C(c,"action")){var e=D(c,"action");if(e)return e}if(!b)return null}a=E(a);a=F(a);return C(a,"action")?D(a,"action"):null}function G(a,b){a=a.__AMP_TOP||a;return D(a,b)}function H(a,b){var c=E(a);c=F(c);return D(c,b)}function E(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}
function D(a,b){C(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function C(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var fa=Object.prototype.hasOwnProperty;function I(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function J(a){return a||{}};function ha(a){a.parentElement&&a.parentElement.removeChild(a)}function ia(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function ja(a){return a.closest?a.closest(".i-amphtml-fie"):ia(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-fie"):!1})};function K(a,b){var c,d=this;this.qa=G(a,"timer");this.va=b;this.ua=c||0;this.J=-1;this.V=0;this.$=!1;this.sa=function(){return d.R()}}K.prototype.isPending=function(){return-1!=this.J};K.prototype.schedule=function(a){var b=a||this.ua;this.$&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.V?(this.cancel(),this.V=c,this.J=this.qa.delay(this.sa,b),!0):!1};K.prototype.R=function(){this.J=-1;this.V=0;this.$=!0;this.va();this.$=!1};
K.prototype.cancel=function(){this.isPending()&&(this.qa.cancel(this.J),this.J=-1)};function ka(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function la(a,b,c){var d=Date.now();this.type=a;this.data=b;this.time=d;this.event=c}
function ma(a,b){this.w=a;this.c=[];this.H=[];this.m=[];this.h=[];this.j=null;this.Aa=b;this.S=!1;this.R=new K(a.ownerDocument.defaultView,this.ka.bind(this));this.na=new t;this.I=Object.create(null);this.ia=this.za.bind(this);this.ga=this.xa.bind(this);this.ha=this.ya.bind(this);this.fa=this.wa.bind(this);this.w.addEventListener("touchstart",this.ia);this.w.addEventListener("touchend",this.ga);this.w.addEventListener("touchmove",this.ha);this.w.addEventListener("touchcancel",this.fa);this.W=!1}
function na(a){var b=void 0===b?!1:b;var c=a.__AMP_Gestures;c||(c=new ma(a,b),a.__AMP_Gestures=c);return c}f=ma.prototype;f.cleanup=function(){this.w.removeEventListener("touchstart",this.ia);this.w.removeEventListener("touchend",this.ga);this.w.removeEventListener("touchmove",this.ha);this.w.removeEventListener("touchcancel",this.fa);delete this.w.__AMP_Gestures;this.R.cancel()};f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.I[d];e||(this.c.push(c),e=new t,this.I[d]=e);return e.add(b)};
f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.I[b]){a.removeAll();a=ka(this.c,function(a){return a.getType()==b});if(0>a)return!1;this.c.splice(a,1);this.m.splice(a,1);this.h.splice(a,1);this.H.splice(a,1);delete this.I[b];return!0}return!1};f.onPointerDown=function(a){return this.na.add(a)};
f.za=function(a){var b=Date.now();this.S=!1;this.na.fire(a);for(var c=0;c<this.c.length;c++)if(!this.m[c]&&(this.h[c]&&this.h[c]<b&&L(this,c),this.c[c].onTouchStart(a))){var d=c;this.H[d]=!0;this.h[d]=0}M(this,a)};f.ya=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)this.H[c]&&(this.h[c]&&this.h[c]<b?L(this,c):this.c[c].onTouchMove(a)||L(this,c));M(this,a)};
f.xa=function(a){for(var b=Date.now(),c=0;c<this.c.length;c++)if(this.H[c])if(this.h[c]&&this.h[c]<b)L(this,c);else{this.c[c].onTouchEnd(a);var d=!this.h[c],e=this.h[c]<b,g=this.j==this.c[c];g||!d&&!e||L(this,c)}M(this,a)};f.wa=function(a){for(var b=0;b<this.c.length;b++){var c=b;this.m[c]=0;L(this,c)}M(this,a)};
function M(a,b){var c=!!a.j||a.S;a.S=!1;if(!c)for(var d=Date.now(),e=0;e<a.c.length;e++)if(a.m[e]||a.h[e]&&a.h[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.Aa||b.preventDefault());a.W&&(a.W=!1,a.ka())}
f.ka=function(){for(var a=Date.now(),b=-1,c=0;c<this.c.length;c++)if(!this.m[c])this.h[c]&&this.h[c]<a&&L(this,c);else if(-1==b||this.m[c]>this.m[b])b=c;if(-1!=b){var d=0;for(c=0;c<this.c.length;c++)!this.m[c]&&this.H[c]&&(d=Math.max(d,this.h[c]-a));if(2>d){a=b;c=this.c[a];for(var e=0;e<this.c.length;e++)if(e!=a){var g=e;this.m[g]=0;L(this,g)}this.m[a]=0;this.h[a]=0;this.j=c;c.acceptStart()}else this.R.schedule(d)}};function L(a,b){a.H[b]=!1;a.h[b]=0;a.m[b]||a.c[b].acceptCancel()}
function N(a,b){this.Ba=a;this.P=b}f=N.prototype;f.getType=function(){return this.Ba};f.signalReady=function(a){var b=this.P;if(b.j)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.m[d]=c+a,b.h[d]=0);b.W=!0}};f.signalPending=function(a){var b=this.P;if(b.j)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.c.length;d++)b.c[d]==this&&(b.h[d]=c+a)};f.signalEnd=function(){var a=this.P;a.j==this&&(a.j=null,a.S=!0)};
f.signalEmit=function(a,b){var c=this.P.I[this.getType()];c&&c.fire(new la(this.getType(),a,b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function oa(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)};function O(a,b,c,d){N.call(this,a,b);this.la=c;this.ra=d;this.j=!1;this.da=this.ca=this.X=this.O=this.pa=this.Z=this.Y=this.D=this.C=this.G=this.F=0}r(O,N);f=O.prototype;f.onTouchStart=function(a){a=a.touches;return this.j&&a&&1<a.length?!0:a&&1==a.length?(this.pa=Date.now(),this.F=a[0].clientX,this.G=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1<=b.length){var c=b[0];b=c.clientX;c=c.clientY;this.C=b;this.D=c;if(this.j)P(this,!1,!1,a);else if(a=Math.abs(b-this.F),b=Math.abs(c-this.G),this.la&&this.ra)(8<=a||8<=b)&&this.signalReady(-10);else if(this.la)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.ra)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};
f.onTouchEnd=function(a){var b=a.touches;b&&0==b.length&&this.j&&(this.j=!1,P(this,!1,!0,a),this.signalEnd())};f.acceptStart=function(){this.j=!0;this.Y=this.F;this.Z=this.G;this.X=this.pa;this.F=this.C;this.G=this.D;P(this,!0,!1,null)};f.acceptCancel=function(){this.j=!1};
function P(a,b,c,d){a.O=Date.now();var e=a.O-a.X;if(!c&&4<e||c&&16<e){var g=oa(a.C-a.Y,e,a.ca),h=oa(a.D-a.Z,e,a.da);if(!c||32<e||0!=g||0!=h)a.ca=1E-4<Math.abs(g)?g:0,a.da=1E-4<Math.abs(h)?h:0;a.Y=a.C;a.Z=a.D;a.X=a.O}a.signalEmit({first:b,last:c,time:a.O,deltaX:a.C-a.F,deltaY:a.D-a.G,startX:a.F,startY:a.G,lastX:a.C,lastY:a.D,velocityX:a.ca,velocityY:a.da},d)}function pa(a){O.call(this,"swipe-xy",a,!0,!0)}r(pa,O);var Q,qa="Webkit webkit Moz moz ms O o".split(" ");function ra(a,b,c){if(2>b.length?0:0==b.lastIndexOf("--",0))return b;Q||(Q=I());var d=Q[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<qa.length;g++){var h=qa[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(Q[b]=d)}return d}function sa(a,b){a=a.style;for(var c in b)a.setProperty(ra(a,c),b[c].toString(),"important")}
function R(a,b,c){var d;(b=ra(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}function S(a,b){for(var c in b)R(a,c,b[c])}function T(a){if("display"in a){if(A.dev)var b=A.dev;else throw Error("failed to call initLogConstructor");b.error("STYLE","`display` style detected in styles. You must use toggle instead.")}return a}function ta(a){var b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")}
function ua(a){for(var b=["transition"],c=0;c<b.length;c++)R(a,b[c],null)};var U;function va(a,b){var c=void 0,d=a,e=b;var g=function(a){try{return e(a)}catch(u){throw self.reportError(u),u;}};var h=wa(),k=!1;c&&(k=c.capture);d.addEventListener("click",g,h?c:k);return function(){d&&d.removeEventListener("click",g,h?c:k);g=d=e=null}}function wa(){if(void 0!==U)return U;U=!1;try{var a={get capture(){U=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return U};function xa(a,b){var c=b,d=va(a,function(a){try{c(a)}finally{c=null,d()}})};function ya(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(b){for(var h=[],l=0;l<arguments.length;++l)h[l-0]=arguments[l];e=a.Date.now();g=h;d||(d=a.setTimeout(c,500))}};var V;function za(a){a=a.ownerDocument||a;V&&V.ownerDocument===a||(V=a.createElement("div"));return Aa}function Aa(a){V.innerHTML=a[0];var b=V.firstElementChild;V.removeChild(b);return b};function Ba(a){return a.classList.contains("i-amphtml-fie")||!!ja(a)};var W=['\n    <i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad">\n      <div>Ad</div>\n      <i-amphtml-ad-close-button class="amp-ad-close-button">\n      </i-amphtml-ad-close-button>\n    </i-amphtml-ad-close-header>'];W.raw=W.slice();
var X={"fade-in":{openStyle:J({opacity:1}),closedStyle:J({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:J({transform:"translate(0, 0)"}),closedStyle:J({transform:"translate(0, 100%)"}),durationSeconds:.2},"fly-in-top":{openStyle:J({transform:"translate(0, 0)"}),closedStyle:J({transform:"translate(0, -100%)"}),durationSeconds:.2}};
function Y(a){var b=AMP.BaseElement.call(this,a)||this;b.ba=null;b.o=null;b.ea=null;b.U=-1;b.K=!1;b.M=null;b.B=!1;b.A=0;b.ma=0;b.T=0;b.aa=null;b.L=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.N=null;b.ja=ya(b.win,function(){var a=B().assertElement(b.o,"E#19457 this.container_");b.scheduleLayout(a);b.scheduleResume(a)});return b}r(Y,AMP.BaseElement);f=Y.prototype;
f.buildCallback=function(){var a=this;this.user().assert(fa.call(X,this.L),"Invalid `animate-in` value %s",this.L);this.element.classList.add("i-amphtml-overlay");this.ea=ea(this.element);Ca(this);this.registerDefaultAction(function(){return Da(a)},"open");this.registerAction("close",this.close.bind(this))};function Ea(a){z(a.element.getElementsByClassName("i-amphtml-element")).forEach(function(b){a.setAsOwner(b)})}
function Fa(a){if(!a.o){var b=a.element;a.B=b.hasAttribute("scrollable");var c=a.getRealChildren();a.o=b.ownerDocument.createElement("div");a.B||a.applyFillContent(a.o);b.appendChild(a.o);c.forEach(function(b){a.o.appendChild(b)});a.B&&(Ea(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){Ea(a);Z(a,a.A,a.A)}),b.addEventListener("scroll",a.oa.bind(a)));if(!a.B){var d=na(b);d.onGesture(pa,function(){})}}}f.layoutCallback=function(){return Promise.resolve()};
function Da(a){if(!a.K){Fa(a);a.M=a.ta.bind(a);a.win.document.documentElement.addEventListener("keydown",a.M);var b=new ca,c=b.promise,d=b.resolve;a.getViewport().enterLightboxMode(a.element,c).then(function(){return Ga(a,d)})}}f.mutatedAttributesCallback=function(a){var b=a.open;void 0!==b&&(b?Da(this):this.close())};function Ha(a){var b=a.o.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}}
function Ga(a,b){function c(){a.ja();b()}var d=a.element,e=X[a.L],g=e.durationSeconds,h=e.openStyle,k=e.closedStyle,l=Object.keys(h).map(function(a){return a+" "+g+"s ease-in"}).join(",");a.T++;a.B&&R(d,"webkitOverflowScrolling","touch");R(d,"transition",l);S(d,T(k));ta(d);a.mutateElement(function(){d.scrollTop=0});Ha(a);Ia(a);a.mutateElement(function(){S(d,T(h))});e=a.o;a.B?(a.oa(),Z(a,a.A,a.A)):a.updateInViewport(e,!0);d.addEventListener("transitionend",c);d.addEventListener("animationend",c);a.scheduleLayout(e);
a.scheduleResume(e);Ja(a,"lightboxOpen");H(a.getAmpDoc(),"history").push(a.close.bind(a)).then(function(b){a.U=b});a.K=!0}function Ia(a){var b=a.element;if(null!=b.getAttribute("close-button")){var c=za(b)(W);a.N=c;xa(c,function(){return a.close()});b.insertBefore(c,a.o);var d;a.measureMutateElement(function(){d=c.getBoundingClientRect().height},function(){c.classList.add("amp-ad-close-header");sa(a.o,{"margin-top":d+"px","min-height":"calc(100vh - "+(d+"px")+")"})})}}
f.ta=function(a){"Escape"==a.key&&(a.preventDefault(),this.close())};f.close=function(){var a=this;this.K&&(this.B&&R(this.element,"webkitOverflowScrolling",""),this.N&&(ha(this.N),this.N=null),this.getViewport().leaveLightboxMode(this.element).then(function(){return Ka(a)}))};
function Ka(a){function b(){d==a.T&&(a.collapse(),a.ja())}var c=a.element,d=++a.T;La(a)?(ua(c),b()):(c.addEventListener("transitionend",b),c.addEventListener("animationend",b));S(c,T(X[a.L].closedStyle));-1!=a.U&&H(a.getAmpDoc(),"history").pop(a.U);a.win.document.documentElement.removeEventListener("keydown",a.M);a.M=null;a.schedulePause(a.o);a.K=!1;Ja(a,"lightboxClose")}function La(a){return"inabox"==y(a.win).runtime||Ba(a.element)}
f.oa=function(){var a=this.element.scrollTop||1;this.A=this.element.scrollTop=a;null===this.aa&&Ma(this,a)};function Ma(a,b){a.aa=G(a.win,"timer").delay(function(){if(30>Math.abs(b-a.A)){a.aa=null;var c=a.A;Z(a,c,a.ma);a.ma=c;a.A=c}else Ma(a,a.A)},100)}function Z(a,b,c){var d=[];Na(a,b,function(b){d.push(b);a.updateInViewport(b,!0);a.scheduleLayout(b)});c!=b&&Na(a,c,function(b){d.includes(b)||a.updateInViewport(b,!1)})}
function Na(a,b,c){a.ba||(a.ba={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.ba.height,e=z(a.element.getElementsByClassName("i-amphtml-element")),g=0;g<e.length;g++){for(var h=e[g],k=0,l=h;l&&a.element.contains(l);l=l.offsetParent)k+=l.offsetTop;var u=2*d;k+h.offsetHeight>=b-u&&k<=b+u&&c(h)}}function Ca(a){var b=a.win;Ba(a.element)&&Oa(b,b.document.body)}
function Ja(a,b){var c=a.win;var d="amp-lightbox."+b;var e=J({}),g={detail:e};Object.assign(g,void 0);"function"==typeof c.CustomEvent?d=new c.CustomEvent(d,g):(c=c.document.createEvent("CustomEvent"),c.initCustomEvent(d,!!g.bubbles,!!g.cancelable,e),d=c);a.ea.trigger(a.element,b,d,100)}
function Oa(a,b){var c={},d=G(a,"ampdoc").getAmpDoc();H(d,"resources").measureMutateElement(b,function(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||I())["background-color"]},function(){c.alreadyTransparent||y().test||B().warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.");sa(b,{background:"transparent"})})}
(function(a){"inabox"==y().runtime&&Oa(window,document.body);a.registerElement("amp-lightbox",Y,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}i-amphtml-ad-close-header{height:60px!important;display:block!important;visibility:visible!important;opacity:0;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:1000!important;display:-webkit-box!important;display:-ms-flexbox!important;display:flex!important;-webkit-box-align:center!important;-ms-flex-align:center!important;align-items:center!important;-webkit-box-pack:right!important;-ms-flex-pack:right!important;justify-content:right!important;-webkit-transition:opacity 0.1s ease-in;transition:opacity 0.1s ease-in}[animate-in=fly-in-bottom]>i-amphtml-ad-close-header,[animate-in=fly-in-top]>i-amphtml-ad-close-header{-webkit-transition-delay:0.2s;transition-delay:0.2s}.amp-ad-close-header{opacity:1!important;box-sizing:border-box;padding:5px;line-height:40px;background-color:#000;color:#fff;font-family:Helvetica,sans-serif;font-size:12px;cursor:pointer}.amp-ad-close-header>:first-child{margin-left:auto!important;pointer-events:none!important}.amp-ad-close-button{display:block!important;background:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='%23fff'%3E%3Cpath d='M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E\") no-repeat;background-position:50%;width:40px;height:40px;pointer-events:none!important;border-radius:40px;margin-left:5px}.amp-ad-close-header:active>.amp-ad-close-button{background-color:hsla(0,0%,100%,0.3)}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-lightbox-0.1.js.map

(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"1905021827420",f:(function(AMP,_){
var k,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var t;a:{var ba={a:!0},u={};try{u.__proto__=ba;t=u.a;break a}catch(a){}t=!1}n=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=n;function w(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function x(a){var b=Object.create(null);if(!a)return b;for(var c;c=ca.exec(a);){var d=w(c[1],c[1]),e=c[2]?w(c[2],c[2]):"";b[d]=e}return b};var y="";self.log=self.log||{user:null,dev:null,userForEmbed:null};var z=self.log;function A(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function B(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");}function C(a,b,c,d,e){A().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function D(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(E(d,b)){var f=F(d,b);if(f)return f}if(!c)return null}a=G(a);a=H(a);return E(a,b)?F(a,b):null}function I(a,b){a=a.__AMP_TOP||a;return F(a,b)}function J(a,b){var c=G(a);c=H(c);return F(c,b)}function G(a){return a.nodeType?I((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function H(a){a=G(a);return a.isSingleDoc()?a.win:a}
function F(a,b){E(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function E(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function K(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function L(a){return a||{}};function da(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};function ea(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function fa(a){return a.closest?a.closest(".i-amphtml-overlay"):ea(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,".i-amphtml-overlay"):!1})};function M(a,b){var c,d=this;this.da=I(a,"timer");this.ja=b;this.ga=c||0;this.F=-1;this.V=0;this.W=!1;this.ea=function(){d.F=-1;d.V=0;d.W=!0;d.ja();d.W=!1}}M.prototype.isPending=function(){return-1!=this.F};M.prototype.schedule=function(a){var b=a||this.ga;this.W&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.V?(this.cancel(),this.V=c,this.F=this.da.delay(this.ea,b),!0):!1};M.prototype.cancel=function(){this.isPending()&&(this.da.cancel(this.F),this.F=-1)};function ha(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function ia(a){if(!ja(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return B().error("MESSAGING","Failed to parse message: "+a,c),null}}function ja(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function N(){var a=100;this.fa=a;this.N=this.Y=0;this.G=Object.create(null)}N.prototype.has=function(a){return!!this.G[a]};N.prototype.get=function(a){var b=this.G[a];if(b)return b.access=++this.N,b.payload};N.prototype.put=function(a,b){this.has(a)||this.Y++;this.G[a]={payload:b,access:this.N};if(!(this.Y<=this.fa)){B().warn("lru-cache","Trimming LRU cache");a=this.G;var c=this.N+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.Y--)}};var O=self.AMP_CONFIG||{},ka={thirdParty:O.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:O.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof O.thirdPartyFrameRegex?new RegExp(O.thirdPartyFrameRegex):O.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:O.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof O.cdnProxyRegex?new RegExp(O.cdnProxyRegex):O.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:O.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:O.localDev||!1};L({c:!0,v:!0,a:!0,ad:!0,action:!0});var P,la;
function ma(a){var b;P||(P=self.document.createElement("a"),la=self.UrlCache||(self.UrlCache=new N));var c=b?null:la,d=P;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=self;if(d.AMP_MODE)d=d.AMP_MODE;else{var f=self.AMP_CONFIG||{},g=!!f.test||!1,m=x(d.location.originalHash||d.location.hash);f=f.spt;var p=x(d.location.search);y||(y=d.AMP_CONFIG&&d.AMP_CONFIG.v?d.AMP_CONFIG.v:"011905021827420");d=d.AMP_MODE={localDev:!1,development:!("1"!=m.development&&!d.AMP_DEV_MODE),examiner:"2"==m.development,filter:m.filter,geoOverride:m["amp-geo"],minified:!0,lite:void 0!=p.amp_lite,
test:g,log:m.log,version:"1905021827420",rtvVersion:y,singlePassType:f}}e=d.test&&Object.freeze?Object.freeze(e):e;c&&c.put(a,e);a=e}return a};function na(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)};var Q,oa="Webkit webkit Moz moz ms O o".split(" ");function pa(a,b){var c;var d=a.style;Q||(Q=K());var e=Q.zIndex;if(!e){e="zIndex";if(void 0===d.zIndex){var f;b:{for(f=0;f<oa.length;f++){var g=oa[f]+"ZIndex";if(void 0!==d[g]){f=g;break b}}f=""}void 0!==d[f]&&(e=f)}Q.zIndex=e}d=e;d&&(a.style[d]=c?b+c:b)};function qa(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function ra(a,b,c){var d=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=qa(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===b){var f=e;break}}f||(f={frame:b,events:Object.create(null)},a.push(f));return f.events}
function sa(a){for(var b=L({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(a){a(b)})}}}
function ta(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=ua(b.data);if(c&&c.sentinel){var e=b.source;var f=qa(a,c.sentinel);if(f){for(var g,m=0;m<f.length;m++){var p=f[m],l=p.frame.contentWindow;if(l){var h;if(!(h=e==l))b:{for(h=e;h&&h!=h.parent;h=h.parent)if(h==l){h=!0;break b}h=!1}if(h){g=p;break}}else setTimeout(sa,0,f)}e=g?g.events:null}else e=f;var q=e;if(q){var r=q[c.type];if(r)for(r=r.slice(),e=0;e<r.length;e++)(0,r[e])(c,b.source,b.origin)}}}};a.addEventListener("message",b)}}
function R(a,b,c,d,e,f){function g(b,d,g){if("amp"==b.sentinel){if(d!=a.contentWindow)return;var m="null"==g&&f;if(p!=g&&!m)return}if(e||d==a.contentWindow)"unlisten"==b.sentinel?h():c(b,d,g)}var m=a.ownerDocument.defaultView;ta(m);d=ra(m,a,d);var p=ma(a.src).origin,l=d[b]||(d[b]=[]),h;l.push(g);return h=function(){if(g){var a=l.indexOf(g);-1<a&&l.splice(a,1);c=l=g=null}}}
function va(a,b,c,d,e){if(a.contentWindow)for(d.type=c,d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp",a=d,e&&(a="amp-"+JSON.stringify(d)),d=0;d<b.length;d++)e=b[d],e.win.postMessage(a,e.origin)}function ua(a){"string"==typeof a&&(a="{"==a.charAt(0)?ha(a,function(a){B().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:ja(a)?ia(a):null);return a}
function S(a,b,c){var d=this;this.h=a;this.R=b;this.B=[];this.la=R(this.h,"send-intersections",function(a,b,g){d.B.some(function(a){return a.win==b})||d.B.push({win:b,origin:g});c(a,b,g)},this.R,this.R)}S.prototype.send=function(a,b){na(this.B,function(a){return!a.win.parent});va(this.h,this.B,a,b,this.R)};S.prototype.destroy=function(){this.la();this.B.length=0};var T=[[300,250],[320,50],[300,50],[320,100]];function U(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function wa(a){for(var b=-Infinity,c=Infinity,d=-Infinity,e=Infinity,f=0;f<arguments.length;f++){var g=arguments[f];if(g&&(b=Math.max(b,g.left),c=Math.min(c,g.left+g.width),d=Math.max(d,g.top),e=Math.min(e,g.top+g.height),c<b||e<d))return null}return Infinity==c?null:U(b,d,c-b,e-d)}function V(a,b,c){return 0==b&&0==c||0==a.width&&0==a.height?a:U(a.left+b,a.top+c,a.width,a.height)};var xa=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1],ya=Date.now();function W(a,b){var c,d=this;this.O=a;this.o=null;this.T=this.X=!1;this.L=null;this.M=a.getViewport();this.Z=new S(b,c||!1,function(){za(d)});this.o=new Aa(function(a){for(var b=0;b<a.length;b++)delete a[b].target;d.Z.send("intersection",L({changes:a}))});this.o.tick(this.M.getRect());this.fire=function(){d.X&&d.T&&d.o.tick(d.M.getRect())}}
function za(a){a.X=!0;a.o.observe(a.O.element);a.O.getVsync().measure(function(){a.T=a.O.isInViewport();a.fire()});var b=a.M.onScroll(a.fire),c=a.M.onChanged(a.fire);a.L=function(){b();c()}}W.prototype.onViewportCallback=function(a){this.T=a};W.prototype.destroy=function(){this.X=!1;this.o.disconnect();this.o=null;this.L&&(this.L(),this.L=null);this.Z.destroy();this.Z=null};
function Aa(a){var b={threshold:xa};this.aa=a;var c=b&&b.threshold;c=c?Array.isArray(c)?c:[c]:[0];for(a=0;a<c.length;a++);this.ka=c.sort();this.U=null;this.ca=void 0;this.j=[];this.w=this.C=null}k=Aa.prototype;k.disconnect=function(){this.j.length=0;Ba(this)};
k.observe=function(a){for(var b=0;b<this.j.length;b++)if(this.j[b].element===a){B().warn("INTERSECTION-OBSERVER","should observe same element once");return}var c={element:a,currentThresholdSlot:0};this.U&&(b=Ca(this,c,this.U,this.ca))&&this.aa([b]);b=G(a);if(b.win.MutationObserver&&!this.C){this.w=new M(b.win,this.ia.bind(this,a));var d=D(a,"hidden-observer");this.C=d.add(this.ha.bind(this))}this.j.push(c)};
k.unobserve=function(a){for(var b=0;b<this.j.length;b++)if(this.j[b].element===a){this.j.splice(b,1);0>=this.j.length&&Ba(this);return}B().warn("INTERSECTION-OBSERVER","unobserve non-observed element")};k.tick=function(a,b){b&&(a=V(a,-b.left,-b.top),b=V(b,-b.left,-b.top));this.U=a;this.ca=b;for(var c=[],d=0;d<this.j.length;d++){var e=Ca(this,this.j[d],a,b);e&&c.push(e)}c.length&&this.aa(c)};
function Ca(a,b,c,d){var e=b.element,f=e.getLayoutBox(),g=e.getOwner(),m=g&&g.getLayoutBox(),p=wa(f,m,c,d)||U(0,0,0,0),l=p;g=f;l=l.width*l.height;g=g.width*g.height;g=0===g?0:l/g;a=a.ka;l=0;var h=a.length;if(0==g)a=0;else{for(var q=(l+h)/2|0;l<q;)g<a[q]?h=q:l=q,q=(l+h)/2|0;a=h}var r=a;if(r==b.currentThresholdSlot)return null;b.currentThresholdSlot=r;c=d?null:c;d=p;a=f;if(l=c)d=V(d,-c.left,-c.top),a=V(a,-c.left,-c.top),l=V(l,-c.left,-c.top);var Ea={time:"undefined"!==typeof performance&&performance.now?
performance.now():Date.now()-ya,rootBounds:l,boundingClientRect:a,intersectionRect:d,intersectionRatio:g,target:e};return Ea}k.ha=function(){this.w.isPending()||this.w.schedule(16)};k.ia=function(a){var b=this,c=J(a,"viewport"),d=J(a,"resources");d.onNextPass(function(){b.tick(c.getRect())})};function Ba(a){a.C&&a.C();a.C=null;a.w&&a.w.cancel();a.w=null};var Da={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};function Fa(a){var b="iframe-messaging";if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,Ga(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=x(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}var g=c;return!!g[b]}
function Ga(a){a:{try{var b=a.document.cookie}catch(g){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==w(c.substring(0,d).trim(),void 0)){a=c.substring(d+1).trim();a=w(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};var Ha="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling".split(" "),Ia=0,Ja=0;function X(a){a=AMP.BaseElement.call(this,a)||this;a.K=null;a.I=!1;a.S=!1;a.D=!1;a.ba=!1;a.P=null;a.h=null;a.J=!1;a.l=null;a.A="";a.iframeSrc=null;a.H=null;a.m=null;return a}var Y=AMP.BaseElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;
if(v)v(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Ka=Object.getOwnPropertyDescriptor(Y,Z);Ka&&Object.defineProperty(X,Z,Ka)}else X[Z]=Y[Z];X.na=Y.prototype;k=X.prototype;k.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
function La(a,b,c){var d=window.location.href;c=void 0===c?"":c;a=a.element;var e=D(a,"url"),f=e.parse(b),g=f.hostname,m=f.protocol;f=f.origin;C(e.isSecure(b)||"data:"==m,"Invalid <amp-iframe> src. Must start with https://. Found %s",a);var p=e.parse(d);C(!Ma(c,"allow-same-origin")||f!=p.origin&&"data:"!=m,"Origin of <amp-iframe> must not be equal to container %sif allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",a);C(!(da(g,
"."+ka.thirdPartyFrameHost)||da(g,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",b);return b}
function Na(a){var b=a.element.getLayoutBox(),c=Math.min(600,.75*a.getViewport().getSize().height);C(b.top>=c,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",a.element,b.top,c)}
function Ma(a,b){var c=new RegExp("\\s"+b+"\\s","i");return c.test(" "+a+" ")}function Oa(a,b){if(b){a=D(a.element,"url").parse(b);var c=a.hash;"data:"==a.protocol||c&&"#"!=c||(a=b.indexOf("#"),b=(-1==a?b:b.substring(0,a))+"#amp=1");return b}}
k.firstAttachedCallback=function(){this.A=this.element.getAttribute("sandbox");var a;if(!(a=Oa(this,this.element.getAttribute("src"))))if(a=this.element.getAttribute("srcdoc")){C(!(" "+this.A+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)var b=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));b=new Uint8Array(a.length);for(var c=0;c<a.length;c++)b[c]=a.charCodeAt(c)}a=
btoa;c=Array(b.length);for(var d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);a="data:text/html;charset=utf-8;base64,"+a(c.join(""))}else a=void 0;var e=a;this.iframeSrc=La(this,e,this.A)};k.preconnectCallback=function(a){this.iframeSrc&&this.preconnect.url(this.iframeSrc,a)};
k.buildCallback=function(){this.K=this.getPlaceholder();this.I=!!this.K;(this.J=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");var a=this.element;if("no"!=a.getAttribute("scrolling")){var b=a.ownerDocument.createElement("i-amphtml-scroll-container");a.appendChild(b);a=b}this.H=a;Pa(this)};
k.onLayoutMeasure=function(){Qa(this);var a=this.element;a:{var b=a.getLayoutBox();var c=b.height;b=b.width;for(var d=0;d<T.length;d++){var e=T[d][0],f=T[d][1];if(!(f>c||e>b)&&20>=c-f&&20>=b-e){c=!0;break a}}c=!1}this.S=c;c=this.element;b=c.getLayoutBox();this.D=10<b.width||10<b.height?!1:!fa(c);if(c=this.S){c=this.win;b=!1;d=0;do Da[a.tagName]?(d++,b=!1):(e=(c.getComputedStyle(a)||K()).position,"fixed"!=e&&"sticky"!=e||(b=!0)),a=a.parentElement;while(a&&"BODY"!=a.tagName);c=!(!b&&1>=d)}this.ba=c;
this.l&&this.l.fire()};function Qa(a){if(a.h){var b=a.getViewport().getLayoutRect(a.h),c=a.getLayoutBox();a.P=V(b,-c.left,-c.top)}}k.getIntersectionElementLayoutBox=function(){if(!this.h)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.P||Qa(this);return V(this.P,a.left,a.top)};
k.layoutCallback=function(){var a=this;C(!this.ba,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.I||Na(this);this.J&&C(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return Promise.resolve();if(this.D&&(Ja++,1<Ja))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
Promise.resolve();var b=this.element.ownerDocument.createElement("iframe");this.h=b;this.applyFillContent(b);b.name="amp_iframe"+Ia++;this.I&&pa(b,-1);this.propagateAttributes(Ha,b);var c=b.getAttribute("allow")||"";c=c.replace("autoplay","autoplay-disabled");b.setAttribute("allow",c);Ra(b,this.A);b.src=this.iframeSrc;this.D||(this.l=new W(this,b));b.onload=function(){b.readyState="complete";a.$();a.D&&(a.iframeSrc=null,I(a.win,"timer").promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);
a.element.setAttribute("amp-removed","");a.h=null}))};R(b,"embed-size",function(b){Sa(a,b.height,b.width)},void 0,void 0,!0);this.I&&R(b,"embed-ready",this.$.bind(this));this.H.appendChild(b);return this.loadPromise(b).then(function(){a.H!=a.element&&I(a.win,"timer").delay(function(){a.mutateElement(function(){a.H.classList.add("amp-active")})},1E3)})};k.unlayoutOnPause=function(){return!0};
k.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.K&&this.togglePlaceholder(!0);this.h=null;this.l&&(this.l.destroy(),this.l=null)}return!0};k.viewportCallback=function(a){if(this.l)this.l.onViewportCallback(a)};k.getLayoutPriority=function(){return this.S?2:this.D?1:AMP.BaseElement.prototype.getLayoutPriority.call(this)};
k.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=Oa(this,b),this.h&&(this.h.src=La(this,this.iframeSrc,this.A)))};k.$=function(){var a=this;this.K&&this.getVsync().mutate(function(){a.h&&(pa(a.h,0),a.togglePlaceholder(!1))})};k.firstLayoutCompleted=function(){};
k.throwIfCannotNavigate=function(){if(!Ma(this.A,"allow-top-navigation"))throw A().createError('"AMP.navigateTo" is only allowed on <amp-iframe> when its "sandbox" attribute contains "allow-top-navigation".');};
function Sa(a,b,c){if(a.J)if(100>b)a.user().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var d,e;b=parseInt(b,10);isNaN(b)||(d=Math.max(b+(a.element.offsetHeight-a.h.offsetHeight),b));c=parseInt(c,10);isNaN(c)||(e=Math.max(c+(a.element.offsetWidth-a.h.offsetWidth),c));void 0!==d||void 0!==e?a.attemptChangeSize(d,e).then(function(){void 0!==d&&a.element.setAttribute("height",
d);void 0!==e&&a.element.setAttribute("width",e)},function(){}):a.user().error("amp-iframe","Ignoring embed-size request because no width or height value is provided",a.element)}else a.user().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element)}
function Pa(a){if(Fa(a.win)){var b=a.element,c=b.getAttribute("src");c&&(a.m=D(b,"url").parse(c).origin);a.registerAction("postMessage",function(b){a.m?a.h.contentWindow.postMessage(b.args,a.m):A().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')},100);if(a.m){var d=10,e=0,f=function(b){if(b.source===a.h.contentWindow)if(b.origin!==a.m)A().error("amp-iframe",'"message" received from unexpected origin: '+b.origin+". Only allowed from: "+a.m);else{if(a.getAmpDoc().getRootNode().activeElement!==
a.h)var c=!1;else c=a.win.document.createElement("audio"),c.play(),c=c.paused?!1:!0;if(c){var g=b.data;try{var l=JSON.parse(JSON.stringify(g))}catch(r){A().error("amp-iframe",'Data from "message" event must be JSON.');return}var h=a.win;b=L({data:l});c={detail:b};Object.assign(c,void 0);"function"==typeof h.CustomEvent?b=new h.CustomEvent("amp-iframe:message",c):(h=h.document.createEvent("CustomEvent"),h.initCustomEvent("amp-iframe:message",!!c.bubbles,!!c.cancelable,b),b=h);var q=D(a.element,"action");
q.trigger(a.element,"message",b,100)}else e++,A().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),e>=d&&(A().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),a.win.removeEventListener("message",f))}};a.win.addEventListener("message",f)}}}k.ma=function(a){this.m=a};function Ra(a,b){var c=b||"";a.setAttribute("sandbox",c)}(function(a){a.registerElement("amp-iframe",X)})(self.AMP);
})});

//# sourceMappingURL=amp-iframe-0.1.js.map